Configs/.config/waybar/config.jsonc

**What it can or may break**
Nothing, all code that was changes was commented and the user can uncomment it to use the code
**What it fixes**
After launch of cliphist via waybar, waybar return to normal and no input/click issues
**Describe what it is**
Some people have the problem that once they click on cliphist any input in waybar is cliphist input. This should give user the option to fix it by uncommenting some lines and deleting the old ones.

Update config.jsonc for cliphist issue

---

Configs/.config/hypr/hyprland.conf

TL;DR: Repeating a keypress used to launch rofi (e.g. $mainMod, A) will close it back.
Hello, 
I hope it's OK to send you pull requests! In my daily use, I find it convenient to repeat the keybind for rofi to close it back. Perhaps you'll find it convenient too?
In my case, I use the "Windows" key without any extra modifier for rofi -show drun, but I did not touch your actual keybinding and left it to "mainMod + A".
Bests,
Hugo

Update hyprland.conf - Toggle rofi instead of purely launching it

---

Configs/.config/waybar/modules/style.css

Hello. I have noticed this behaviour in the waybar.
The fix addresses the issue and seems to have no side effects. 
Thanks!

The glyph was being cut due to a window padding of 0

---

Configs/.config/waybar/modes/wb_bottom_01.jsonc
Configs/.config/waybar/modes/wb_top_01.jsonc
Configs/.config/waybar/modules/battery.jsonc
Configs/.config/waybar/modules/pulseaudio.jsonc
Configs/.config/waybar/modules/style.css

I noticed that the battery for Waybar is on your to-do list, so I thought I'd chip in with my edited Waybar config. Additionally, I have optionally added a percentage to the system audio icon to indicate the current volume.

Waybar battery and system audio icon update

---

Configs/.config/hypr/themes/Catppuccin-Latte.conf
Configs/.config/hypr/themes/Catppuccin-Mocha.conf
Configs/.config/hypr/themes/Decay-Green.conf
Configs/.config/hypr/themes/Material-Sakura.conf
Configs/.config/hypr/themes/Rose-Pine.conf
Configs/.config/hypr/themes/Tokyo-Night.conf

Hello,
In the last Hyprland update `blur` variables have been moved under a new subcategory `decoration:blur`, see [Release v0.28.0 - hyprwm/Hyprland](https://github.com/hyprwm/Hyprland/releases/tag/v0.28.0).
I have therefore applied these changes to all config files under [Configs/.config/hypr/themes/](https://github.com/prasanthrangan/hyprdots/tree/main/Configs/.config/hypr/themes).
P.S.: I love these dots, thank you <3

Fixing all Hyprland themes after v0.28.0 blur changes

---

Configs/.config/hypr/hyprland.conf
Configs/.config/hypr/keybindings.conf
Configs/.config/swappy/config
Scripts/restore_cfg.lst

Hello Prasan,
Screenshots (full screen) are currently saved under ~/Apps/grim, as per this keybinding:
`bind = $mainMod ALT, P, exec, grim ~/Apps/grim/$(date +'%y%m%d_%Hh%Mm%Ss_screenshot.png') # print current screen`
~/Apps is not a default path for Arch, and most distros I know of.
Meanwhile, cropped screenshots are saved under whatever is the default for Swappy on your distro (on Arch, for example: https://man.archlinux.org/man/swappy.1.en)
This is inconsistent, makes me a sad potato, and wakes me up at night. What about placing screenshots by default under ~/Pictures, which is much more common? Users could define their own path by overwriting a variable in userprefs.conf
Install scripts could also make sure ~/Pictures exist, and if not create it (which again, strikes me as …

Use a unified path to save screenshots (for grim/swappy)

---

Scripts/create_cache.sh

Hey Prasan,
I noticed that  you are storing thumbnails for swww (under .cache) directly on Git. The goal of this commit is to reduce the size of the repository by removing cached files that can be generated locally by the user.
To avoid generating thumbnails "on the fly", I have created a script to generate the cache during the installation process. 
Adding this step during the installation process would avoid having users face a slow-down the first time they would open, for example, the theme or wallpaper selector.
There's a -f (for force) flag that you can pass to delete the existing .cache/theme_abc folders and recreate them from scratch. Might be useful if you delete / change wallpapers down the line.
I am not sure where you'd like to include this script in the installation process …

Auto-generate wallpaper thumbnails

---

Configs/.config/hypr/hyprland.conf
Configs/.config/wlogout/layout_1

I think it makes more sense to lock the screen when you suspend the computer or been idle for a certain amount of time.

Lock before suspending

---

Configs/.config/hypr/scripts/gpuinfo.sh

This script will first check for dedicated NVIDIA or AMD GPUs, and if none is found, it will check for integrated Intel GPUs. If neither dedicated nor integrated Intel GPUs are found, it will check for integrated AMD GPUs and collect their information. The script will then display GPU information with the appropriate emoji for the temperature.

Updated gpuinfo.sh -- Integrated + AMD gpu support

---

Configs/.config/waybar/modules/gpuinfo.jsonc

I think the following
it's more clear than the fire icon.

Change temp icon in gpuinfo

---

Scripts/restore_fnt.sh

Hello hello,
Very simple change, this was always failing on my side because I do not have grub installed, and so the folder /usr/share/grub didn't exist, and couldn't be created by my local user without sudo.
Bests,
Hugo

Rerun the folder creation as root if it fails with current user

---

Configs/.config/hypr/scripts/systemupdate.sh

I discovered that clicking the system update never worked and I discovered it is because the script doesn't launch the update process with the installed AUR wrapper and instead hardcodes yay. This will fix it.

Fix system update execution to work with any AUR wrapper

---

Configs/.config/hypr/keybindings.conf

**Usage:**
`$mainMod SHIFT, $CONTROL, ArrowKeys [←→↑↓]`
**alternative option:**
The caviate is that we have to modify the **Spotify vol ctrl**.
_I suggest:_
`$mainMod $CONTROL, ALT, Up/Down [↑↓]`
So we could move active windows around with:
`$mainMod $CONTROL, ArrowKeys [←→↑↓]`

feat: add keybinds to move active window around with arrow keys

---

Configs/.config/hypr/wallbash/dunst.dcol

My main system automatically starts Dunst again after killall Dunst with
``` 4|cat $HOME/.config/dunst/dunst.conf $HOME/.config/dunst/Wall-Dcol.conf > $HOME/.config/dunst/dunstrc && killall dunst|.config/dunst/Wall-Dcol.conf     ``` 
But my **other** laptop won't restart Dunst after killall dunst leaving my laptop to have no Dunst running unless I run ``` dunst ``` manually. 
I do not know what should be the expected behavior. But appending   ``` && dunst & disown ```  to
``` 4|cat $HOME/.config/dunst/dunst.conf $HOME/.config/dunst/Wall-Dcol.conf > $HOME/.config/dunst/dunstrc && killall dunst && dunst &|.config/dunst/Wall-Dcol.conf  ``` fixes it . 
It won't cause a regression to my Main system BTW. 
This may be due to the my **other** laptop so we can close this if this is not relevant to …

Dunst won't start itself after Theme/wallpaper etc change

---

Configs/.config/wlogout/layout_1

Hi there folks, I messed up in my previous PR but yeah it happens, was my first PR anyway. So, I just came across this problem of swaylock getting in the way of system suspension and the culprit was this line in .config/wlogout/layout_1, it was not daemonized `swaylock && systemctl suspend` which was then converted to `swaylock -f && systemctl suspend`.
So this PR just tries to fix this issue. I have tested it and it works well. Please check by yourself too.

Daemonize swaylock before suspending the system [Try 2]

---

Configs/.config/hypr/keybindings.conf

This PR adds what I find an essential element for keyboard users to fully enjoy the workspace experience and that is the ability to switch between relative workspaces and move windows between relative workspaces.
-  Switch to relative workspaces using `mainMod + CTRL +  [left, right]` 
(functionality was present for mouse but missing for keyboard users)
-  Move windows between relative workspaces using `mainMod + CTRL + ALT +  [left, right]`    
(could not use `mainMod + CTRL + shift + [left, right] `  as it is already bound to moving window inside a workspace)
and a tiny bit more
-  Switch to first empty workspace using `mainMod + CTRL +  [down] `
(In case if anybody wants an empty workspace instantly without moving through all the workspaces one by one, although this workspace can be in …

Switch between rel workspaces, move windows to rel workspaces

---

Scripts/custom_apps.lst

Adding trash can in terminal for trash management & to prevent accidental deletion of files <br>
[trash-cli](https://github.com/andreafrancia/trash-cli) available in both:
[arch repo](https://archlinux.org/packages/extra/any/trash-cli/) <sup>***(Flagged out-of-date on 2023-09-24)***</sup> &
[trash-cli-git](https://aur.archlinux.org/packages/trash-cli-git)<sup>AUR</sup> <br>
usage: check [documentation](https://github.com/andreafrancia/trash-cli#usage)
it can also be automated: [how-to-auto-delete-files-older-that-30-days](https://github.com/andreafrancia/trash-cli#how-to-auto-delete-files-older-that-30-days)
Example usage:<br>
>`trash-list` makes it easy to check the files & directory inside the trash
>`trash-empty` empties trash can with confirmation (y/n)<br>

feat: add trash management in terminal

---

Configs/.config/hypr/keybindings.conf

These changes allow the user to quickly open the system monitor (htop) and enable/disable waybar

Shortcut to open the system monitor (htop) and enable/disable waybar

---

Configs/.config/hypr/keybindings.conf
Configs/.config/hypr/scripts/sysmonlaunch.sh

This fork stems from a comment i made in #416 regarding a keybind to open a htop. 
I'm not completely against how this was done its just my personal opinion that if we are setting a keybind to open an application we should be making sure that application is being installed (added to the package list) other wise users may see the update press the keybind and then log an issue when the application does not open. 
To combat this i've whipped up a quick script to check if a user has one of the following [htop,btop,top] and open that in the default terminal set in the keybindings.conf. 
Tests i've run are as follows : 
- Checked keybind with htop installed - htop opens in kitty
- Checked keybind with btop installed - btop opens in kitty
- Checked with neither htop/btop installed - Top opens in …

added script to launch users preferred system monitor.

---

Configs/.config/waybar/modules/workspaces.jsonc

Fixed waybar
*Note: Latest waybar updates sucks. Its tapping 1-3 cores at 100% -- I'm going to downgrade for the time being but I wanted this to be fixed for the updates coming
This is fixed in [0.9.24](https://github.com/Alexays/Waybar/releases/tag/0.9.24)

Waybar Persistent Workspaces update -- Deprecated value removed 

---

Configs/.config/hypr/scripts/batterynotify.sh

Continuation for  #414 
Discussion on Issue #411 
+ Non-intrusive Notification :bow:
+ Acts like the old script but prompts every 5% instead of per 5 minutes. (Upon reaching threshold) Stops if interval < 5.
+ Appending "on" "--dock" will Give Plug In/Out/Full
+ TUI
+ Error handling report on terminal 
+ Default for Battery full notification interval is set to 1 day.
+ Verbose mode for Debugging. 
+ Defaults on Screenshot. 
+ Should Fix If Device reports "Not" "Not charging" "Not Charging" or "Not"*
-- The script is too elaborate and could/should be refactored further.

[Enhancement] Battery Notification +Error Handlers

---

Scripts/restore_cfg.sh

My system can't handle it anymore haha(But maybe not just my system). The constant updating and caching wallpapers makes my system too hot and takes up a lot of time to complete.
This is the shortest way I know to conserve the cache without configuring git. 
But please Tell me what checks we need to avoid errors. Or this approach is not good and there is a better way. 
For context: 
I fork the repo then On the fork, I added the cache folder so that it will be imported on ./restore.sh but by doing this like I said I should fork the repo or git add .../.cache which is not very intuitive for others, and sometimes git reports conflicts.

Reuse the cached Wallpaper

---

Scripts/custom_hypr.lst

I noticed the screenshot script (mainMod + P) does not freeze the screen when used. After some searching, I realized that hyprpicker-git needs to be installed in order for grimblast's --freeze option to work.
Thank you so much for creating hyprdots!

add hyprpicker-git to use grimblast --freeze

---

Configs/.zshrc

Brings back the directories that are suggested by the list commands.

fix(eza): fix `ls` dirs suggestions

---

Configs/.config/waybar/modules/workspaces.jsonc

Is this okay? I have this case that I thought my workspace 1 had an active window. So can we remove any persistent workspaces?  
I usually use a laptop to swipe and I find this slightly annoying hehe. If  You guys want a home workspace maybe we could implement 1 soon.

Default : No Persistent Workspaces 

---

Configs/.config/waybar/modules/mediaplayer.py
Configs/.config/waybar/modules/spotify.jsonc

- Modified `write_output()` function in `mediaplayer.py` to take a tooltip argument
- Added tooltip functionality to spotify widget to show the full title and artist that is playing
Changes that I made are minimal. If there is anything specific you want me to fix please let me know here :)

Added tooltip functionality to spotify widget

---

Configs/.config/hypr/scripts/globalcontrol.sh

Maybe This can be useful for future scripts, in case the user just uses ``` ./install.sh -r ```.  
I can only think of #435 
Usage: 
source ```  ~/.config/hypr/scripts/globalcontrol.sh ```
then
``` 
#Dependency check
check pkg1 pkg2 pkg3 
```

Fn Check Dependency

---

Configs/.config/hypr/scripts/swwwallselect.sh
Configs/.config/hypr/scripts/themeselect.sh

When selecting a theme or wallpaper the rofi selector always start at the first item. I found it more intuitive to have it start at the currently applied theme/wallpaper

feat: theme selector from current

---

Scripts/custom_hypr.lst

Changed the repo to the official version instead of git
```
hyprland-git --> hyprland
```
**Why?** - hyprland-git can't get installed, so the whole install script breaks at this part.
It's just a minor change that people don't get confused and can install everything without problems.

Minor change

---

Scripts/install.sh

#586 
hyprland-nvidia-git no longer needed.
https://github.com/hyprwm/Hyprland/pull/3957
we should use hyprland-git also in nvidia.

remove deprecated hyprland-nvidia-git

---

Configs/.config/hypr/scripts/cliphist.sh
Configs/.config/hypr/scripts/gamelauncher.sh
Configs/.config/hypr/scripts/globalcontrol.sh
Configs/.config/hypr/scripts/logoutlaunch.sh
Configs/.config/hypr/scripts/rofiselect.sh
Configs/.config/hypr/scripts/screenshot.sh
Configs/.config/hypr/scripts/sddmwall.sh
Configs/.config/hypr/scripts/swwwallbash.sh
Configs/.config/hypr/scripts/swwwallpaper.sh
Configs/.config/hypr/scripts/swwwallselect.sh
Configs/.config/hypr/scripts/testrunner.sh
Configs/.config/hypr/scripts/themeselect.sh
Configs/.config/hypr/scripts/wallbashdunst.sh
Configs/.config/hypr/scripts/wallbashkvm.sh
Configs/.config/hypr/scripts/wallbashrofi.sh
Configs/.config/hypr/scripts/wallbashspotify.sh
Configs/.config/hypr/scripts/wallbashtoggle.sh
Configs/.config/hypr/scripts/wallbashypr.sh
Configs/.config/hypr/scripts/wbarconfgen.sh
Configs/.config/hypr/scripts/wbarstylegen.sh
Configs/.config/neofetch/config.conf
Scripts/.extra/restore_app.sh
Scripts/create_cache.sh
Scripts/themepatcher.sh

Currently, the scripts will fail if a user chooses to customize the location of their config directory with `$XDG_CONFIG_HOME` or their data directory with `$XDG_DATA_HOME`. This isn't too uncommon and major desktop environments respect this choice as well.
This PR [implements the crutial parts of the XDG Base Directory Specification](https://xdgbasedirectoryspecification.com); the variables are first read, and only fall back to the values of `$HOME/.config` and `$HOME/.local/share`, respectively, if they are null or an empty string.
There are some other areas that have not been converted. Namely, the `.css` files (this can be searched with the search query `"$HOME"`) and the `restore_cfg.list`, since it is unclear whether the `${VAR:-fallback}` construct is supported. In any case, that …

Use `XDG` Base Directory variables where possible

---

Scripts/custom_hypr.lst

Adding Hyprland-Git back to the custom_hypr.lst as the official hyprland version is 5 releases behind the GIT, breaks changes in the themes. 
Fixes: #592

FIX: Add Hyprland-Git 

---

Configs/.config/hypr/scripts/batterynotify.sh

Since compound statements in Bash (and POSIX shell) need to be terminated with a semicolon, this fixes that.

Add missing terminating semicolon in compound statement

---

Configs/.config/hypr/scripts/themeswitch.sh

This will add support for applications that rely only on gtk4 by symlinking the installed gtk theme directory to `~/.config/gtk-4.0`. Works as intended when I tested it.

Add support for gtk4 specific applications

---

Configs/.config/hypr/scripts/globalcontrol.sh

https://github.com/prasanthrangan/hyprdots/commit/732d7dc5d538a8bb045da6d36a0aced3113be76d changed a line that changed the way waybar (and possibly other configs) got there colors. For a while i noticed that waybar looked weird, like text was displaying red. Found that it was using my wallpaper for colors rather than the current gtk theme, looked and found the commit that changed that, i don't know if it was intentional but i think by default it should use the current gtk theme.
So tl;dr, this doesn't necessarily fix anything but just changes using wallpaper colors for the theme back to using the current gtk theme.

Partial revert to commit in globalcontrol.sh

---

Scripts/restore_cfg.sh

Since ./cfg_backups gives the distinction already can we have this, please? This makes it faster to read and also easy to script. Thanks! 
``` 
❯ date +'%Y_%b_%d_%a_%Hh%Mm%Ss.bak'
2023_Dec_08_Fri_23h00m01s.bak
```

BkpDir: 231209_13h02m30s

---

Configs/.config/hypr/hyprland.conf

Disable Anime Waifu as some users are embarrassed in the office. 😅
Real reason is it looks unnatural upon startup as the waifu is displayed few ms before swww shows up
- [*] **Other** (provide details below)
- [ x I have tested my code locally and it works as expected.

[Disable] Hyprland waifu,wallpaper.splash

---

Configs/.config/waybar/config.jsonc
Configs/.config/waybar/modules/network.jsonc

New waybar network module style.
Now by default only icon (for economy space).
Tooltip with full network information.
Alt view with upload and download speed.
NerdFontIcons

Waybar Network Module Styles 

---

Configs/.config/waybar/modules/bluetooth.jsonc

Discussion here
#757 
Added battery percentage for Bluetooth devices with battery.  
See the file and uncomment this part if the user prefers a certain device 
```
"format-device-preference": [ "device1", "device2" ], // preference list deciding the displayed device If this config option is not defined or none of the devices in the list are connected, it will fall back to showing the last connected device.
```
format-device-preference:
typeof: array
A ranking of bluetooth devices, addressed by their alias. The order is from first displayed to last displayed.
If this config option is not defined or none of the devices in the list are connected, it will fall back to showing the last connected device.
Add …

[Feature]Display Bluetooth Battery

---

Scripts/restore_shl.sh

Fixes this error : 
```
❯ ./restore_shl.sh
[SHELL] detected // zsh
intalling zsh plugins (git sudo zsh-256color zsh-autosuggestions zsh-syntax-highlighting)
./restore_shl.sh: line 57: [: too many arguments
[SKIP] zsh is already configured...
```
Also ensures $USER only matches the exact user 
```
if [[ "$(grep "/${USER}:" /etc/passwd | awk -F '/' '{print $NF}')" != "${myShell}" ]] ; then
```
Added / and : around $USER to match exactly. If system has multiple users e.g "khing" "khing-test"

[FIX] restore_shl.sh

---

Configs/.config/hypr/scripts/swwwallbash.sh
Configs/.config/hypr/scripts/swwwallpaper.sh
Configs/.config/hypr/scripts/swwwallselect.sh
Scripts/create_cache.sh

~This is buggy/. Transitions on swww glitches the GIF. Can be fixed with
``` swww kill && swww init ``` but that would remove capability to have fancy transitions
For now we can check is file is .gif then  gives flags or something to kill and initialize swww again or
do not give transitions for .gif images(kill and init is faster than this ).~
> There should be a better solutions so I need some eyes here :
Solution: Instead of setting a symlink for the wallpaper use the real path 
* Sorry for always having an MR entry, it might be annoying. 
https://github.com/prasanthrangan/hyprdots/assets/53417443/f65fa17f-b12e-49ac-9611-e0e702765ff6
https://github.com/prasanthrangan/hyprdots/assets/53417443/ea46cf9e-35 …

[Ready]  Support .gif files

---

Configs/.config/hypr/keybindings.conf

Forces VSCode to run in Wayland rather than Xwayland
Due to a current bug in electron, some electron apps don't respect Ozone environment variables. This change forces VSCode to run in Wayalnd when using the keybinding rather than xwayland.
This will also resolve issues with blurriness when scaling vscode, such as when using hidpi monitors.
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if …

Forces VSCode to run in Wayland rather than Xwayland

---

Configs/.config/hypr/scripts/cpuinfo.sh

Added support for Ryzen CPU on Waybar module "cpuinfo.sh"
Waybar module for CPU temp returning: "Null" for Package ID 0 as Package ID 0 is not present for Ryzen series CPU's.

Support for Ryzen CPU's 

---

Configs/.config/hypr/wallbash/kitty.dcol

Commented out some color override as these are critical on terminal
Goal of this change is to give clarity. 
Based of zsh
+ The prompt uses colors [ 7 , 4 , 0  ]
+ The commands and executables is color [ 2 ]
+ Here's some overrides for the color.
WARNINGS, ERRORS, ALERTS are not visible if we override these colors.
Visibility in Terminal is vital, therefore I commented out these colors. 
```
color1 
color3 
color5 
color6 
color8 
color9 
color10
color11
color12
color13
color14
color15
```
My bad for this frequent change.

[Enhance] Clarity for Kitty Dcol

---

Scripts/create_cache.sh

Some users do not use code and deleted it. 
Also, if it is okay, I added '|| true' upon ext installation as this gives an exit status but no error messages. Which leads to user needs to run ./install.sh for every theme.(Maybe connectivity issue). The extension still be added by running ``` create_cache.sh ``` again. (faster than full ./install.sh) 

Create cached if no 'code'

---

Configs/.config/hypr/scripts/screenshot.sh

Turning off Hyprshade while taking Screenshot, this may come in handy if using nightlight to remove double layyer of hyprshade
Added a current Hyprshade config remembering script 
oes not fix a bug or add a feature but makes something clearer for devs)
- [ x] **Other** 
Before 
After 
This won't affect the people who don't have hyprshade

Temporarily Turning off hyprshade while taking screenshot

---

Configs/.config/hyprdots/scripts/gpuinfo.sh

Currently, the script gets the max power limit, which is usually not active by default. With this change, it will get the currently active power limit, which should show more accurate power usage information.
Feedback very welcome.

gpuinfo.sh: use limit instead of max_limit for nvidia-smi PL query

---

Scripts/custom_hypr.lst

- Just added `kservice5 kdbusaddons5 kfilemetadata5 kconfig5 kcoreaddons5` to fix "open with" menu in dolphin
- I had an issue where I couldn't see any apps in "open with" and files couldn't be opened with vscode (which is the default app), other file managers could open it with no issues.
- Installing those packages fixed the problem.

Fix: Added packages needed for "open with" in dolphin

---

Configs/.config/hyprdots/scripts/swwwallbash.sh

Will skip wallbash if directory of target file does not exist 
Example if directory ``` /home/khing/.config/cava/ ``` does not exist then skip wallbash for cava
Before: 
After:
> [!Note]
> Wallbash requirement:parent directory should exist for the target file .

[Wallbash] Skip non existing Target file

---

Configs/.config/hyprdots/scripts/gamemode.sh

- Fix gamemode.sh won't do anything
- Disabled waybar transition when gamemode was enabled (due to uncanny effect)
- [x ] **Bug fix** (non-breaking change which fixes an issue)
- [ x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [x ] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ x] I have tested my code locally and it works as expected.
- [x ] All new and existing tests passed.
The output for the hyprctl command seems to be changed and hyprctl reload was resetting the changes made by  hyprctl --batch 'command')
This may be an …

Gamemode.sh temporary fix for Hyprland V0.37.1.1

---

Configs/.config/hyprdots/scripts/quickapps.sh
Configs/.config/hyprdots/scripts/themeswitch.sh
Configs/.config/waybar/config.jsonc
Configs/.config/waybar/modules/spotify.jsonc
Scripts/restore_fnt.sh

I think I will take a break here. With these changes I think I've achieved at least an MVP if you will. I manually deployed Hyprdots as best as I knew. I placed the repo in my home dir, copied all the relevant dirs from `Configs/.config/` to `~/.config`, fixed all the symlinks to point to `/home/my-user/...` instead of the default `/home/tittu/...`, edited the `CloneDir` in `Configs/.config/hyprdots/scripts/globalcontrol.sh`. Basically I tried to manually do the jobs of `restore_fnt.sh, restore_cfg.sh, restore_lnk.sh`.
When I rebooted into Hyprland it kinda worked. I had the Catpuccin theme, waybar on the bottom (though the icons and text were too small!), an indicator for the currently active window, working icons for wlogout (though its colors and icons were missing), cliphist, the …

MVP Nixos patches

---

Configs/.local/share/bin/keybinds_hint.sh

Just found out that keycodes do have a different variable than key
https://github.com/prasanthrangan/hyprdots/issues/1302#issuecomment-2053705146
As of the moment keycode mapping is not yet implemented 
This MR gives as the ability to use 'code:n' or keycodes on our keybinds hint and can actually be converted to the prefered symbole. 
e.g
keycode:61  is '?'
UPDATE: 
Also added an option to map the keycode manually ( key codes are actually tied to some keyboard layout so would be better to map it manually https://www.toptal.com/developers/keycode/table )

Ability to map keycode to a certain symbol for keybinds hint

---

Configs/.local/share/bin/systemupdate.sh

HyDE has transitioned to using fastfetch rather than neofetch by default.
This change allows the systemupdate.sh script to execute correctly on a system that does not have the 'neofetch' package.

 fix: systemupdate.sh with fastfetch

---

Configs/.local/share/bin/themeswitch.sh

Themeswitch script was creating a broken symlink for gtk-4.0 theme pointing to `/usr/share/themes`, however actual theme dir is `~/.themes`. 

Fix gtk4 themeDir location in `themeswitch.sh`

---

Configs/.config/waybar/modules/updates.jsonc
Configs/.local/share/bin/wallbashqt.sh

Fixes!
Some scripts don't have access/rights to some variables compared to when run with ` hyprctl dispatch exec ` .
Thanks to @hoodust  @Skerse

Fixes some ENV block errors and ensure shell are run inside hyprland ENV

---

Configs/.config/hypr/keybindings.conf

- [x ] **Bug fix** (non-breaking change which fixes an issue)
- [ Maybe ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- fixing the keybind that causes the waybar to change state (killed/active) (discussed on https://github.com/kRHYME7/Hyde-cli/issues/22#issuecomment-2078778091 )
- Made the sysmon (btop/htop) floating.

Fixed certain clashing keybindings

---

Configs/.config/waybar/modules/style.css
Configs/.config/waybar/style.css

Waybar context menus had malformed icons, it is not round (or square) but like oval (or rectangle).
1. Changing `min-height` in css improves icons making them look more pretty.
2. Additional `min-height` for separator prevents a menu separator to have increased height.
I have tested this change with different themes and font sizes (from 8 to 16) and didn't notice any problems

Change waybar style `min-height` to 16px for tray context menu to improve context menu icons

---

Configs/.config/fastfetch/config.jsonc

I think fastfetch must have done a change that increased the amount of information the default gpu module gives? This just formats it to how it was before.
As of right now: 
With the format applied:

fix: only use format '2' for gpu module

---

Configs/.config/hyde/wallbash/Wall-Ways/discord.dcol

This is an attempt to improve the discord theme. Now there are shades of the background color so it results into more beautiful theme. Also no more invisible text as mentioned in this issue (#1407). 

Adjusting the discord palette generator and fixing the invisible text

---

Configs/.config/hypr/hyprland.conf

`Config error in file /home/<user>/.config/hypr/hyprland.conf at line 105: config option < master:new_is_master > does not exist`
After updating to the latest version of hyprland, specifically v.041.2, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5 the option master: new_is_master used before does not longer exist. My fixed is done looking at the hyprland website under 
https://wiki.hyprland.org/Configuring/Master-Layout/
It is the fourth option listed under the category name "master"

fixed master layout after updating hyprland to version v0.41.2

---

Configs/.config/waybar/modules/mpris.jsonc

I fixed the not themed pause button from the mpris module from waybar. 
Before:
After:
This is my first pull request 🥵

Fix the not themed pause button

---

Configs/.config/hyde/wallbash/Wall-Dcol/kvantum/kvconfig.dcol

This is a little modification to improve the interface on menu items from Dolphin.
- [x ] **Other** (provide details below)
The addition of 4 properties for text margin in the wallbash kvantum theme file.

Margin to menu items added

---

Configs/.config/rofi/styles/style_1.rasi
Configs/.config/rofi/styles/style_10.rasi
Configs/.config/rofi/styles/style_11.rasi
Configs/.config/rofi/styles/style_12.rasi
Configs/.config/rofi/styles/style_2.rasi
Configs/.config/rofi/styles/style_3.rasi
Configs/.config/rofi/styles/style_4.rasi
Configs/.config/rofi/styles/style_5.rasi
Configs/.config/rofi/styles/style_6.rasi
Configs/.config/rofi/styles/style_7.rasi
Configs/.config/rofi/styles/style_8.rasi
Configs/.config/rofi/styles/style_9.rasi

When trying to open an application in rofi that doesn't exist an unstyled error message with white background is shown.
I added the following code to hyprdots rofi styles in order to center the text and inherit the theme colors.
```rasi
// Error message //
error-message {
text-color:                  @main-fg;
background-color:            @main-bg;
text-transform:              capitalize;
children:                    [ "textbox" ];
}
textbox {
text-color:                  inherit;
background-color:            inherit;
vertical-align:              0.5;
horizontal-align:            0.5;
}
``` 
Fixes #1695

Resolves #1695. Improve rofi's error message style

---

Configs/.config/hypr/nvidia.conf

According to https://wiki.hyprland.org/Nvidia/ the environment variable WLR_NO_HARDWARE_CURSORS is deprecated and we should use cursor:no_hardware_cursors instead.
Without this change, the mouse lags and CPU spikes like crazy, from personal experience and from (https://github.com/prasanthrangan/hyprdots/issues/1739)

fix: Fix deprecated no_hardware_cursors environment variable

---

Configs/.config/waybar/modules/taskbar.jsonc

Add mapping for datagrip to show correct icon in taskbar
the datagrip icon was displayed as the file icon

feat: add datagrip icon in taskbar

---

Configs/.config/baloofilerc
Scripts/restore_cfg.lst

`baloo` package in installed as dependency of dolphin and provides file indexing and search features, which does not work without plasma desktop:
```sh
$ balooctl6 status
Baloo Index could not be opened
```
```sh
$ balooctl6 status
Baloo is currently disabled. To enable, please run balooctl enable
```
This PR add config for disabling file indexing, which result in one less process running. Not much, but why not.

Feature: Disable KDE baloo file indexing

---

Scripts/custom_hypr.lst

`rofi-lbonn-wayland-git` aur package is not versioned properly and have frozen on version `1.7.5.wayland1.r42` which means if you want updated version, this package should be synced explicitly using `yay/paru -S rofi-lbonn-wayland-git`.
Recently in main arch repo [`rofi-wayland`](https://archlinux.org/packages/extra/x86_64/rofi-wayland/) package has appeared. It is versioned properly and has version `1.7.5+wayland3` which corresponds to [lbonn/rofi repo](https://github.com/lbonn/rofi/releases)
The only one reason of this PR is to provide feature to update `rofi` automatically using `<yay/paru> -Syu` without necessity to update package explicitly.

Feature: Change rofi package from `rofi-lbonn-wayland-git` to `rofi-wayland`

---

Configs/.config/hypr/hyprland.conf

This PR adds the ability to enable NumLock by default on startup in Hyperland. This change is essential because NumLock gets disabled whenever Hyde is updated, and having NumLock enabled by default is crucial for many users who rely on it.
In .config/hypr/hyprland.conf in the input configuration section, I've added the line:
```bash
numlock_by_default = true
```
This ensures that NumLock is enabled automatically when the system starts, providing a better user experience.
I believe enabling NumLock by default is crucial for user convenience, especially since it tends to reset after updates. This change will help maintain a consistent experience.

Enable numlock on startup

---

Configs/.local/share/bin/keyboardswitch.sh

In 0.43 was introduced new [`all` parameter for `hyprctl switchxkblayout` command](https://wiki.hyprland.org/Configuring/Using-hyprctl/#switchxkblayout).
> DEVICE can also be current or all, self-explanatory. Current is the main keyboard from devices.
Using this parameter simplifies `keyboardswitch.sh` script: no need to query all keyboards and loop them.

Use hyprland 0.43 capabilities for switching keyboard layout

---

Scripts/install.sh

Added `yay-bin` and `paru-bin` installation choices.
~~`paru` has compilation issues sometimes, `paru-bin` is overall faster (precompiled binary) and using it has no real downsides.~~

Add `-bin` packages options for AUR helpers

---

Configs/.local/share/bin/cpuinfo.sh

Two small things are done in this PR:
1. Eliminated excessive `sensors` call for AMD CPUs in `cpuinfo.sh` script
2. Added rounding of CPU temperature to integer value to match style of GPU temperature (make sense only for AMD CPUs, Intel temps are already integers)

Optimization for CPU info script

---

Configs/.config/waybar/modules/window.jsonc

1000 characters makes the hyperland/window super long compard to other modules and takes up quite the space
Before:
After:

fix: decrease window text to 100 characters

---

Configs/.config/hyde/hyde.conf
Configs/.config/waybar/modules/cava.jsonc
Configs/.local/share/bin/waybar_cava.sh

Customization capability for waybar cava
custom
standbymode = 0 : clean (default) 
standbymode = 1 : blank space
standbymode = 2 : full bar preview
standbymode = 3 : low -est bar will be displayed
when set 
width: 
range (It isn't good to touch this though, It helps to fine-tune if user wants to add more bar chararacters  )
* Disowns the parent shell so that we can strip off some memory 
* --restart just kills the cava instance then the waybar revives it after 1 second. 
* Added sleep for Cava for better power saving mode when nothing is playing then sed do not write anything
2 monitors so 2 instance 
cava sleeping
I can't capture it but if Cava is in idle mode it fetches for input every second hence in average it uses 1.2% peak when reading at 100ms and 0.2% peak when reading at 1000ms …

improved waybar cava

---

Configs/.local/share/bin/swwwallbash.sh
Scripts/themepatcher.sh

Closes https://github.com/prasanthrangan/hyprdots/issues/1904
Prevents [confusion with theme mode and wallbash mode ](https://github.com/prasanthrangan/hyprdots/pull/1889) 
Reason: 
It's the feat req of Khing. 
This way theme maintainers can optionally ship the intended dominant color files.  
TODO: 
* themepatcher.sh should support if file exist
* Hyde theme import should also be updated

[theme maintainers] option to strictly implement colors for themes

---

Configs/.local/share/bin/logoutlaunch.sh

wlogout button color only followed the dcol_mode of the orignal cached wallpaper (wall.dcol) and not the color scheme set in hypr.theme or theme.dcol in theme mode 
this fixes the issues and makes it so that it follows hypr.theme or theme.dcol (if present) in theme mode and wall.dcol of the original cached wallpaper in wallbash auto/dark/light modes.
**before :**
**after :**

wlogout variable btn_col now follows theme.dcol and hypr.theme in theme mode

---

Configs/.config/hypr/windowrules.conf

Spotify now uses "spotify" instead of "Spotify" as class name so this pr makes it so that window rules get followed for both
We have the initial title window rule as well but doing it with class name seems better and consistent for me

Update spotify windowrule

---

Configs/.config/hypr/windowrules.conf

VSCode 1.95 have different class name with lowercase letters. I have changed opacity rule to be applied correctly
Output of `hyprctl clients`
```
Window 5d9524c7f420 -> Release Notes: 1.95.0 - Visual Studio Code:
mapped: 1
hidden: 0
at: 1930,47
size: 945,1023
workspace: 8 (8)
floating: 0
pseudo: 0
monitor: 1
class: code
title: Release Notes: 1.95.0 - Visual Studio Code
initialClass: code
initialTitle: Visual Studio Code
pid: 256694
xwayland: 0
pinned: 0
fullscreen: 0
fullscreenClient: 0
grouped: 0
tags: 
swallowing: 0
focusHistoryID: 1
```

Change opacity rule for new version of vscode

---

Configs/.config/dolphinrc
Configs/.config/kdeglobals

Made background transparent in kdeglobals so it does not interfere with theming.
Moved ColorScheme=* from DolpinRc to kdeglobals
Type of change
[x ] Bug fix (non-breaking change which fixes an issue)
Checklist
[x] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
[x] My code follows the code style of this project.
[x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
My change requires a change to the documentation.
I have updated the documentation accordingly.  
I have added a changelog entry.                                                                            ?
I have added necessary comments/documentation to my code.
I have added …

fix: Dolphin/KDE fix for themes

---

Configs/.config/dunst/dunst.conf
Configs/.config/dunst/dunstrc

Dunst 1.12 have chages in `height` implementation now only value is not implemented as "maximum height", but it is implemented as "fixed height", which leads to unnecesary space consumed by notification.
Quote from docs:
> Dunst v1.11 and older do not support a dynamic height and height accepts a single value whose behaviour is equivalent to (0, value).
I do not use `0,300` but use `140,300` instead to preserve some margin between icon and notification border
This small patch changes behavior like it was on older dunst versions.
Also changed `offset` value to new format, stated in [dunst docs](https://dunst-project.org/documentation/#Global-section)

Dunst: Patch config to display notifications correctly on >= 1.12

---

Configs/.config/hypr/windowrules.conf

transparency effect for chrome AUR was previously (google-chrome) or (google-chrome-stable) now is (Google-chrome)

efecto de transparencia para Google chrome AUR

---

Configs/.config/waybar/modules/cpuinfo.jsonc
Configs/.config/waybar/modules/gpuinfo.jsonc
Configs/.local/share/bin/cpuinfo.sh
Configs/.local/share/bin/gpuinfo.sh

This is a copy of #952 but updated so that it could be auto-merged

UPDATED perf: optimize performance of waybar cpuinfo and gpuinfo modules

---

Configs/.local/share/bin/gpuinfo.sh

On AMD GPUs `gpuinfo.sh` had one minor problem: `Utilization` always show "lowest" gauge icon not respecting the actual gpu load because of empty "utilization" variable on [row 154 ](https://github.com/prasanthrangan/hyprdots/blob/master/Configs/.local/share/bin/gpuinfo.sh#L154)
```json
{"text":" 38°C", "tooltip":"AMD Navi 14\n Temperature: 38°C ❄️\n󰾆 Utilization: 0.2%\n󱪉 Power Usage: 7 W\n Clock Speed: 492 MHz"}
{"text":" 86°C", "tooltip":"AMD Navi 14\n Temperature: 86°C 🌋\n󰾆 Utilization: 96.4%\n󱪉 Power Usage: 122 W\n Clock Speed: 850 MHz"}
```
This change rename `gpu_load -> utilization` in `amd_GPU()` function to match intel & nvidia functions.
Add any other context about the …

Fixup `gpuinfo.sh` for amd gpu
