Configs/.config/swww/swwwallpaper.sh
Simplified code logic in functions Wall_Prev()  and Wall_Next().
Thank you for maintaining this amazing project!
=> Refactor Wall_Prev and Wall_Next

Configs/.config/wlogout/layout, Configs/.config/wlogout/style.css
This is a minor refactor of the wlogout module, including the addition of hibernate and suspend functions, as well as a revision of the colour contrast. Consider this a suggestion, as these files will likely be generated based on the theme and scale factor. 
Thank you!
=> Minor wlogout refactor

Configs/.config/dunst/icons/mic/muted-mic.svg, Configs/.config/dunst/icons/mic/unmuted-mic.svg, Configs/.config/hypr/hyprland.conf, Configs/.config/hypr/scripts/volumecontrol.sh
=> Add FN+MuteMic for laptop users 

Configs/.config/hypr/themes/Catppuccin-Latte.conf, Configs/.config/hypr/themes/Catppuccin-Mocha.conf, Configs/.config/hypr/themes/Decay-Green.conf, Configs/.config/hypr/themes/Material-Sakura.conf, Configs/.config/hypr/themes/Rose-Pine.conf, Configs/.config/hypr/themes/Tokyo-Night.conf
Set the 'resize_on_border' parameter to true in the hyprland configuration, allowing for window resizing by dragging the border.
=> Enable resizing on border

Configs/.config/dunst/dunstrc, Configs/.config/hypr/scripts/brightnesscontrol.sh
- Update dunstify notification on ~/.config/hypr/scripts/brightnesscontrol.sh 
- Added brightness-control format to  ~/.config/dunst/dunstrc
=> Update the brightness notification

Configs/.config/waybar/config.ctl
Add battery for laptop users in waybar
=> Add battery icon for laptop users

Configs/.config/hypr/hyprland.conf, Configs/.config/hypr/scripts/batterynotify.sh
Make a script for battery warning notification for battery low and full
=> script for battery warning notifiction

Configs/.config/dunst/dunstrc
Closes #98
Notes:
- Assign open context menu to left-click
=> add rofi context menu for dunst

Configs/.config/hypr/scripts/logoutlaunch.sh
toggles wlogout menu instead of creating multiple menus on top of each other
=> toggles wlogout menu

Configs/.config/hypr/scripts/batterynotify.sh, Configs/.config/waybar/modules/cliphist.jsonc, Configs/.config/waybar/modules/mode.jsonc
create more space in modules clipboard & theme change mode 
before the change 
after change
=> More space in modules

Configs/.config/hypr/keybindings.conf
Requirement, install hyprshade for night light blue light filter 
And night light key and printscreen key for screenshot
=> Add night light key and printscreen  key 

Configs/.config/hypr/scripts/gpuinfo.sh
When the driver inst loaded, the message get a little strange. I use gpu passthrough sometimes so the driver change and this code made the things works.
before:
after:
=> Gpu message format

Configs/.config/waybar/modules/gpuinfo.jsonc, Configs/.config/waybar/modules/mpris.jsonc, Configs/.config/waybar/modules/window.jsonc
Symptoms: 
-Overshooting Waybar
-Too Long Text on waybar.
Solution:
+I just Added an upper/max limit for texts on waybar. Please let me know if this can mess up other configs.  
*Please Let me know also if other modules have these symptoms.
*I chose 1000 as the max-length to cater to wider screens. 
Thanks !
=> Text/Label on Waybars for small monitor fx

Configs/.config/hypr/scripts/cliphist.sh
+ Clipboard follows mouse (Sorry I used Windows Clipboard )
+ Respect monitor scaling (sizing? )
+Respect monitor position(for weird monitor arrangement)
+follows   $HOME/.config/rofi/clipboard.rasi for height and width
Please Leave Comments for improvements!
https://github.com/prasanthrangan/hyprdots/assets/53417443/0d7d5c27-0b5e-4cfe-8dad-4332af6f8615
=> Clipboard (Update cliphist.sh)

Configs/.config/hypr/keybindings.conf, Configs/.config/hypr/userprefs.conf
=> Add '-x' argument to pkill for exact process match.

Configs/.config/hypr/wallbash/dunst.dcol
``` killall -SIGUSR2 ``` this Signal can be use given that  dunst should already be running.
=> killall -SIGUSR2 dunst

Configs/.config/waybar/modules/backlight.jsonc
=> Update backlight icons

Configs/.config/hypr/scripts/sddmwall.sh
sddmwall.sh was broken on my multiple monitor setup.  "awk" was returning 3 lines which broke "cp"
=> Update sddmwall.sh - for multiple monitor support

Configs/.config/hypr/scripts/gpuinfo.sh
Tested -- Works and removes the N/A in power usage
=> Adjusted power limit -- gpuinfo.sh

Scripts/restore_cfg.sh
=> Added Check for the cache Directory.

Configs/.config/hypr/hyprland.conf
empty input properties cause this issue.
=> kb_options does not follow userperfs

Configs/.config/hypr/keybindings.conf
**Keybinds**: volume & backlight work when the display is locked
**Adjust**: resize speed slightly
=> Minor adjustments

Scripts/custom_apps.lst
At first I thought it should be an optional pkg, but changed it to be included as part of the first install.
Since we're rolling & new people are coming, KSK Royal made a video about the project.
And with an issue like #496, it's useful to have this.
=> Add `downgrade` to initial install

Configs/.zshrc
- deleted all the auto-generated comments on the .zshrc
- added some comments of my own to each part of it
- detect aurhelper once and use it
- slight (maybe personal preferences) modifications to eza/pacman aliases
=> Quality of life updates to the .zshrc 

Configs/.config/hypr/keybindings.conf, Configs/.config/hypr/scripts/screenshot.sh, README.md
- Added `sf` option for `screenshot.sh` (snip,frozen)
- Added hotkey `SUPER` + `ctrl` + `P` to snip with frozen screen
=> Add separate hotkey for frozen screenshots

README.md
I want to have this merged since there are some people that might get confused by how hyprdots works.
- Now explains how to update the dots (You did say here: https://github.com/prasanthrangan/hyprdots/discussions/262, but I think that it would be useful for some people to just see it on the front page)
- Gives a warning about installing on a previously installed desktop (Might prevent issues like this from happening: https://github.com/prasanthrangan/hyprdots/issues/630)
=> Modify README to give more information

Scripts/custom_hypr.lst
This covers now almost all implemented functions of Hyprdots.
=> Added hyprdots-ctl

Configs/.config/hypr/scripts/batterynotify.sh
+ Config file for batterynotify.sh
+ Can execute a command on status Changes
+ Support for multiple Batteries
+ Accidentally reduces tick events when using for loop that wildcards[*]  ([Means lesser Power usage ](https://github.com/prasanthrangan/hyprdots/issues/641#issuecomment-1870477530))
#695 
#641 
#472 
#694 
Making a config file for batterynotify.sh to run something on status changes.
Usage:
upon running:
The Config file:
Nothing changed on implementation, converted the CLI part into a persistent config file located at ```  ~/.config/hypr/hyprdots-ctl/batterynotify.conf ``` . and Just added an Elaborate support for multiple batteries.
=> [Bug fix + FEATURE ] : Batterynotify.sh

Configs/.config/hypr/scripts/brightnesscontrol.sh
Add finer brightness control
In low light environments users often need more precise control over brightness adjustment particularly when the brightness is already set to a low level. This commit adds improved brightness control when the brightness is less than 10%. The brightness can be adjusted with 1% incremental/decremental adjustment instead of the default 5% step, addressing the limitation of only having one level of decreased brightness after the 10%.
=> feat: add finer brightness control

Configs/.config/fish/config.fish, Configs/.zshrc
Considering how much I use this project, only felt fitting to help out back. 
Adding a couple of shortcuts that're absolute time-savers (especially that cd one, credit goes to Derek from DistroTube)
Fixing an issue that happens with ssh and kitty, the terminal emulator has trouble opening some TUI applications through ssh and rerouting them through a kitten of the same name fixes the issue!
Thanks for the great project! 🤍
Notes
FP:  Spelling mistake
=> Add a couple of shortcuts and a "bug"-fix for kitty

Configs/.config/hypr/scripts/gpuinfo.sh, Configs/.config/waybar/modules/gpuinfo.jsonc, Configs/.config/waybar/modules/memory.jsonc
Animated the icons in the gpuinfo module and memory module. The thermometer icons and utilization icons (inclusive of those in tooltip) changes the state depending on the current level of temperature and utilization. 
Also included some minor UI improvements.
Look carefully at the thermometers & speedometers (uh oh, ignore the extra one, that's for cpu info, I'll add it in a different PR)
I don't like people editing my comments, I'll cry :-/
=> feat: Animate waybar gpuinfo and memory module

Configs/.config/hypr/windowrules.conf
This windowrules config change should make ArmCord look better and close to the themes of hyprdots.
=> config: Adding ArmCord to windowsrules config

Configs/.config/hypr/scripts/wallbashkitty.sh, Configs/.config/hypr/wallbash/kitty.dcol
=> Kitty dominant color

Configs/.config/hypr/scripts/swwwallpaper.sh
Is it okay to only call swwwallpaper script one at a time? 
Fixes this 
https://github.com/prasanthrangan/hyprdots/issues/855
https://github.com/prasanthrangan/hyprdots/issues/815
=> Single Call of Swwwallpaper 

Scripts/create_cache.sh
What is ${OPTARG}?  For now, I give ${2} if the ${OPTARG} is not available. 
=> [FIX] create_cache.sh -c borke

Configs/.config/hyprdots/scripts/gamemode.sh, Configs/.config/hyprdots/scripts/wallbash.sh
Try this algorithm to better capture dominant colors
K-means clustering is a technique that groups similar data points (in this case, colors) into clusters based on their similarity. The -kmeans option allows you to reduce the number of colors in an image by specifying the desired number of clusters (k).
=> Update wallbash.sh, changing -color by -kmeans

Configs/.config/hyprdots/scripts/wallbashdiscord.sh, Configs/.config/hyprdots/wallbash/discord.dcol
Vesktop.dcol
#931 
@Enigma1309 
@RookiexCookie
@akashgagda
=> Discord Wallbash

Configs/.config/hyprdots/scripts/cpuinfo.sh
>The cpu model display is incomplete and cannot be displayed after locale.conf is configured.
locale.conf is not configured
configured locale.conf(~/.config/locale.conf)
```conf
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:en_US
```
>Fixed model and maximum …
=> fix(cpuinfo): model display and cpu maximum frequency

Configs/.config/hypr/windowrules.conf, Configs/.config/hyprdots/scripts/gpuinfo.sh, Configs/.config/hyprdots/scripts/themeswitch.sh, Configs/.config/hyprdots/scripts/volumecontrol.sh
=> [Extra] fixes 

Scripts/custom_hypr.lst
``` hyprdots-ctl ``` 
Comply with VCS standards.
=> Fix yay won't auto update

README.md
- [ x ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ x ] I have read the [CONTRIBUTING](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md) document.
- [ x ] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
=> docs: Change typo "toogle" to "toggle" in README

Configs/.config/hyprdots/wallbash/Wall-Dcol/waybar.dcol, Scripts/themepatcher.sh
https://github.com/prasanthrangan/hyprdots/pull/1188#issue-2207131396
=> Themepatcher for HyDE

Configs/.config/waybar/modules/workspaces.jsonc
Switching workspace up or down via scrolling mouse in respective direction when hovering workspace module
=> Switching workspaces via mouse scrolling

Configs/.config/hypr/animations.conf, Configs/.config/hypr/hyprland.conf, Configs/.config/hypr/keybindings.conf, Configs/.config/hypr/monitors.conf, Configs/.config/hypr/monitors.t2, Configs/.config/hypr/nvidia.conf, Configs/.config/hypr/themes/common.conf, Configs/.config/hypr/userprefs.conf, Configs/.config/hypr/userprefs.t2, Configs/.config/hypr/windowrules.conf
Doesn't add or remove any features, or fix any bugs. This is simply to make most of the configs more consistent and make better sense, hopefully?
=> Refactor: hypr configs for better formatting and consistency

Configs/.local/share/bin/swwwallpaper.sh, Scripts/custom_hypr.lst
[swww v0.9.2](https://github.com/LGFae/swww/releases/tag/v0.9.2) fix  no wallpaper problem #1204
=> chore: switch swww to the stable version  (close #1204)

Configs/.config/hypr/windowrules.conf
=> feat: add vscode insiders in  windowrules.conf

Configs/.config/hypr/hyprland.conf, Configs/.config/hypr/keybindings.conf, Configs/.config/hypr/userprefs.conf, Configs/.config/hypr/userprefs.t2, README.md
Complete readme overhaul. It is now up-to-date, more informational, and in my opinion, has a lot better formatting and cleaner code. Other than that, it remained mostly the same in terms of what there is.
Also did some minor changes to hypr configs, some of which i missed in my last pull request, and fit well with the readme overhaul. ~~Additionally in keybindings.conf, i removed the `$mainMod` variable as it was kind of useless in my opinion.~~
=> README.md overhaul + minor changes

Configs/.local/share/bin/brightnesscontrol.sh, Configs/.local/share/bin/screenshot.sh, Configs/.local/share/bin/themeselect.sh, Configs/.local/share/bin/wallbashtoggle.sh
After update the dunst notificaton the dunst not show some notification icons like screenshot, brightness, themeselector and wallbash so i fix  these icons issue
=> Fix notification icons problem

Configs/.p10k.zsh
the p10k nordvpn module causes the shell to hang on new instance for 5-10 seconds if disconnected from internet. Disabling this fixes the issue
=> fix: .p10k.zsh nordvpn module hanging shell

Configs/.local/share/bin/volumecontrol.sh
Nothing special, just a small typo in file `Configs/.local/share/bin/volumecontrol.sh`
=> Just a Very Small Typo

README.md
Adding discord badge
standalone badge
badge with logo
=> add: discord badge

Configs/.config/fastfetch/config.jsonc
Adds jsonschema spec for fastfetch config. Should provide intellisense on ides when editing file
=> feat(fastfetch): add jsonschema spec for intellisense on ides

Configs/.local/share/bin/wbarconfgen.sh, Scripts/custom_hypr.lst
Fixes:
#1483 
#1476 
#1477 
* Will merge this for now as this is not breaking change and should fix issues above.
* the change in waybar is not breaking but helps us to have consistent waybar layout when using Garuda hyprland.
Please revert later if not intended 😁
=> Quick fixes and non breaking, Needs to be merged immediately 

README.md
=> fix: discord rate limit problem

Configs/.p10k.zsh
=> fix: add quiet flag to .p10k instant prompt

Configs/.config/waybar/config.jsonc, Configs/.config/waybar/modules/notifications.jsonc
remove a duplicate key on waybar config.json
=> fix: remove duplicate key on waybar

Configs/.config/hypr/keybindings.conf, README.md
Adds keys to move between the stacked windows in a group activated with MOD+G
more context [wiki.hyprland.org/Configuring/Dispatchers/#grouped-tabbed-windows](https://wiki.hyprland.org/Configuring/Dispatchers/#grouped-tabbed-windows)
(if …
=> feat(keybinds): add keybinds to move between windows in a group

Configs/.config/dunst/dunst.conf, Configs/.config/dunst/dunstrc, Configs/.config/hyde/hyde.conf, Configs/.local/share/bin/batterynotify.sh, Configs/.local/share/bin/gpuinfo.sh, Configs/.local/share/bin/keybinds_hint.sh, README.md, Scripts/install_pst.sh, Scripts/restore_shl.sh
Spells fixes. Old pr got corrupted
=> fix: spell issues

Configs/.local/share/bin/swwwallpaper.sh
`/.local/share/bin/swwwallpaper.sh` change
add's `swww query && swww restore` to the local/share/bin/swwwallpaper.sh file to fix broken changes to swww-git
Bug Fix
-  [x] My commit message follows the [commit guidelines](https://github.com/prasanthrangan/hyprdots/blob/main/CONTRIBUTING.md#git-commit-messages).
=> Fix: swww-git fix to resolve breaking change on loading wallpapers.

Configs/.config/waybar/modules/pulseaudio.jsonc, Configs/.local/share/bin/volumecontrol.sh
=> feat: output sink selector

Configs/.p10k.zsh
This just replaces the tux icon with arch icon
Before:
After:
=> fix(prompt): replace tux icon with arch icon

Configs/.local/share/bin/volumecontrol.sh
- Ensured Proper `OPTARG` Handling: Made sure `player_name` is captured and used correctly.
BEFORE:
AFTER:
=> fix: volumecontrol not correctly capturing the player name

Configs/.config/waybar/config.jsonc, Configs/.config/waybar/modules/clock.jsonc
This improves calendar tooltip styling, now font and size are applied correctly
=> Improve calendar tooltip style in waybar

Configs/.local/share/bin/themeswitch.sh
follow up for https://github.com/prasanthrangan/hyprdots/pull/1689
=> feat: Accepts Hyprland Variable for gtk Theme and Icon

Configs/.local/share/bin/swwwallbash.sh
follow up for https://github.com/prasanthrangan/hyprdots/pull/1691
=> feat: respect the color scheme set in hypr.theme when in theme mode

Configs/.config/fastfetch/config.jsonc
=> Fastfetch-added OS age and Uptime

Configs/.local/share/bin/wbarconfgen.sh
=> [waybar] Capability to have user modules by adding "#tag" 

Configs/.config/hypr/keybindings.conf, README.md
=> Added keybinds hint shortcut

Configs/.config/hypr/windowrules.conf
Window rule added for About Firefox window
- [x ] **Other** (provide details below)
Specific window rule
=> Float mode to "About Firefox" window

Configs/.local/share/bin/notifications.py, Configs/.local/share/bin/wbarconfgen.sh
Show notification  history  uptop 10 notifications
=> Feature : Show 10 notification history in tooltip

Configs/.local/share/bin/swwwallcache.sh
`convert` is outdated and is replaced with the current and correct usage of `magick`
=> replace convert with magick

Configs/.local/share/bin/wallbashcode.sh
This should fix the wallbashcode errors.
=> Updated wallbash code script

CONTRIBUTING.md, Configs/.local/share/bin/gamelauncher.sh, Configs/.local/share/bin/gpuinfo.sh, Configs/.local/share/bin/keybinds_hint.sh, Configs/.local/share/bin/screenshot.sh
=> fix: spells

Configs/.config/code-flags.conf
Removed spaces before the flags on "code-flags.conf" that made the flags not apply and open them as files
=> fix: Fixed vs-code flags not applying

Configs/.config/spotify-flags.conf
=> fix: remove space from the flag in spotify

Configs/.config/hypr/keybindings.conf, Configs/.local/share/bin/cliphist.sh
Added Following Features In Clipboard
1.Clear History At Once
2.Delete Specific Clips From History
3.Support For Adding And Managing Favourites
You Can Check The Video Here
https://youtu.be/EzqB5o0s_lk
=> Added Much More Features in Clipboard

Configs/.local/share/bin/wallbashcode.sh
Added support for wallbash theming on Cursor IDE for now with manual intervention of installing the theme https://www.cursor.com/how-to-install-extension
@kRHYME7
=> feat: Add wallbash Theme support for Cursor(IDE)

Configs/.local/share/bin/wallbashcode.sh
=> fix regression for vscodium

Configs/.config/fastfetch/config.jsonc
Replaces sort and head with shuffle . 
=> feat: use shuffle for faster

Configs/.zshrc
This update refines the .zshrc file by adjusting formatting and improving comments for clarity and consistency. Key changes include:
- Reformatted comments to enhance readability and maintain uniformity.
- Minor syntax adjustments for a cleaner look.
- Ensured code style is consistent throughout the script.
=> Refine .zshrc formatting and comments

Configs/.local/share/bin/themeswitch.sh, Configs/.local/share/bin/wbarconfgen.sh
=> use _ intead of - so we can parse it as var

Configs/.config/code-flags.conf
closes #1937 
this fixes the following bugs
- vscode does not remember recently opened files / directories
- can not launch multiple instances of vscode using the ```code``` command
=> fix: remove extension development path from vs code config

README.md
=> fix: dont brick systems

README.md
Added my project supporting HyDE on NixOS and home-manager
[https://github.com/richen604/hydenix/tree/main](
https://github.com/richen604/hydenix/tree/main)
=> added Hydenix to readme

Scripts/themepatcher.sh
=> preparation

Configs/.config/hyde/hyde.conf, Configs/.config/hypr/keybindings.conf, Configs/.config/waybar/modules/header.jsonc, Configs/.config/waybar/modules/notifications.jsonc, Configs/.local/share/bin/wbarconfgen.sh, README.md
This was bugging me when i was changing my waybar layout. the toggle waybar keybind now reloads the config.jsonc file when being toggled on
Upstream change to waybar broke this module, minor change in format string fixes it.
=> Waybar bugfix and minor QOL change

Configs/.config/hypr/themes/theme.conf
**Summary of the changes and which issue is fixed.**
Changed decoration:drop_shadow to decoration:shadow:enabled.
**Relevant motivation and context (if applicable).**
Fixes an error in the config file from breaking changes in hyprland v0.45.0.
**List any dependencies that are required for this change. (e.g., packages or other PRs)**
hyprland==v0.45.0
=> fix: Change drop_shadow to new convention from v0.45.0

Configs/.config/dolphinrc
dolphin fix for font and folder highlight color issue
**old:**
**new:**
=> update dolphinrc to fix font and highlight issues

Configs/.local/share/bin/swwwallbash.sh, Configs/.local/share/bin/themeswitch.sh, Configs/.local/share/bin/waybar_cava.sh
=> [performance] reload on exit

Configs/.local/share/bin/brightnesscontrol.sh
- This is done so that waybar scroll on brightness can be done without pushing notifications on user for every scroll up or down
- Also this would not interfere with old brightness code as the quiet mode flag is disabled by default. So even if there is missing `q` flag in calling brightness script  the function will work as intended.
- Since PR [#2029](https://github.com/prasanthrangan/hyprdots/pull/2029) changed the brightness module. Tthere is a bug on scrolling in which the mouse pointer becomes unresponsive when the brightness is increased and decreased rapidly while an app is running on same workspace. 
- Bug video is included
The mouse pointer when moved left and right means the scrolling function …
=> feat: add quiet mode for brightnesscontrol script and refactor code

Configs/.config/hypr/animations.conf
Add a different animation for specialworkspace, setting it apart from regular workspace
=> Add a different animation for specialworkspace

Configs/.config/waybar/modules/idle_inhibitor.jsonc
- Added tooltip for caffeine mode
- Changed icon so that it can get recongnised for its functionality
=> refactor: Add tooltip and changed icon in idle_inhibitor module waybar

Configs/.config/kitty/kitty.conf, Configs/.config/kitty/userprefs.conf, Scripts/restore_cfg.lst
I use custom keybindings and some other settings for kitty terminal and have created small feature which allows to have `userprefs.conf` file for kitty configuration, which is not overwritten during updates.
=> Feature: `userprefs.conf` support for kitty terminal

Configs/.config/fastfetch/config.jsonc
=> Feat: Enhanced Fastfetch

Configs/.config/waybar/modules/github_hypr.jsonc, Configs/.config/waybar/modules/github_hyprdots.jsonc
You will be sent to the hyprdots repository with a single click
=>  github_hyprdots.jsonc

Configs/.config/waybar/modules/github_hyprdots.jsonc
=> xdg-open github_hyprdots.jsonc

Configs/.config/waybar/modules/keybindhint.jsonc
a detail that just by putting the mouse you will see what that icon is for
=> tooltip-format keybindhint.jsonc

Configs/.config/kitty/kitty.conf
This PR adds a new feature to improve cursor visibility. kovidgoyal/kitty#7970
=> Feat: add cursor trail animation in kitty

README.md
=> docs: add deprecation message
